Кнопка возврата наверх
slavaver/web-course-site pull request #19
Opened 2023-04-07 20:45 UTC by DimDimich-creator

![image](https://user-images.githubusercontent.com/59178589/230675338-933b1200-047e-4b88-90a6-eae4953ae669.png)
![image](https://user-images.githubusercontent.com/59178589/230675359-336eeb96-ac80-435c-942c-f145fef97aee.png)
close #3

2023-04-07 21:58 UTC, XMadFoX commented on src/components/navigation/ButtonTop.astro
> +    '<svg xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 96 960 960" width="48"><path d="M450 896V370L202 618l-42-42 320-320 320 320-42 42-248-248v526h-60Z"/></svg>';
Зачем через js создавать? Еще для стилей тут используется tailwindcss если что

2023-04-07 22:09 UTC, DimDimich-creator commented on src/components/navigation/ButtonTop.astro
> +    '<svg xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 96 960 960" width="48"><path d="M450 896V370L202 618l-42-42 320-320 320 320-42 42-248-248v526h-60Z"/></svg>';
Мне  написать html кнопку, задать ей стили

И только повесить листенеры?

2023-04-10 00:56 UTC, XMadFoX requested changes

2023-04-10 00:56 UTC, XMadFoX commented on src/components/navigation/ButtonTop.astro
> +  document.body.appendChild(button);
В layout же импортируется, зачем appendChild?

2023-04-10 00:56 UTC, XMadFoX commented on src/components/navigation/ButtonTop.astro
> +<button id="back-to-top-btn" class="fixed bottom-5 right-5"
aria-label добавить нужно

2023-04-10 00:56 UTC, XMadFoX commented on src/components/navigation/ButtonTop.astro
> +      button.style.display = "none";
Думаю лучше [переключать классы](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList).
Так же было бы неплохо сделать анимацию (через прозрачность например)

2023-04-10 17:35 UTC, XMadFoX commented on src/components/navigation/ButtonTop.astro
> +<div class="hidden sm:block">
Почему ты решил не показывать на телефонах? @DimDimich-creator

2023-04-10 18:11 UTC, DimDimich-creator commented on src/components/navigation/ButtonTop.astro
> +<div class="hidden sm:block">
Стрелочка закрывает контент

2023-04-10 19:39 UTC, XMadFoX commented on src/components/navigation/ButtonTop.astro
> +<div class="hidden sm:block">
Сделай чтобы не закрывала

2023-04-10 19:39 UTC, XMadFoX requested changes
Следует использовать цвета темы
Так же наверное лучше добавить фон для кнопки

2023-04-11 12:37 UTC, XMadFoX approved these changes

2023-04-14 09:09 UTC, merged