Toc
slavaver/web-course-site pull request #23
Opened 2023-05-29 23:04 UTC by DimDimich-creator

![image](https://github.com/slavaver/web-course-site/assets/59178589/4fd07fba-f620-471b-8e13-6e7ae0e5d295)

2023-05-29 23:55 UTC, XMadFoX requested changes

2023-05-29 23:55 UTC, XMadFoX commented on src/components/navigation/TOC.astro
> +    padding-top: 100px !important;
без important, глобальных стилей, и margin/padding, используй scroll-margin https://tailwindcss.com/docs/scroll-margin

2023-05-29 23:55 UTC, XMadFoX commented on src/components/navigation/TOC.astro
> +<div class={hid}>
может лучше conditional rendering?

2023-05-30 00:14 UTC, DimDimich-creator commented on src/components/navigation/TOC.astro
> +<div class={hid}>
> может лучше conditional rendering?

В astro он есть?

2023-05-30 00:16 UTC, XMadFoX commented on src/components/navigation/TOC.astro
> +<div class={hid}>
@DimDimich-creator да, суля по всему как и в react. {condition && <Component />}

2023-05-30 16:38 UTC, XMadFoX requested changes

2023-05-30 16:38 UTC, XMadFoX commented on src/components/navigation/TOC.astro
> +  }
почему не через tailwindcss классы?

2023-05-30 16:38 UTC, XMadFoX commented on astro.config.mjs
> +    integrations: [tailwind()]
???

2023-05-30 20:50 UTC, XMadFoX commented on src/components/navigation/TOC.astro
> +  }
в атрибуте class, в строке через пробел
Например `<div class="bg-red-700">`

2023-05-30 21:20 UTC, DimDimich-creator commented on src/components/navigation/TOC.astro
> +  }
> в атрибуте class, в строке через пробел
> Например `<div class="bg-red-700">`

Astro сам собирает markdown и нельзя обратиться по другому к тегам

2023-08-31 13:41 UTC, slavaver commented
Идеи кода взял из вашего коммита и добавил меню.

2023-08-31 13:41 UTC, closed without merging